### ISSUE TITLE
Parts tables is keep growing and growing

### ISSUE THREAD

**Issue by thebitllc** [DariusIII/newznab-tmux#39]
My parts table keeps growing and growing. Not sure what I have done wrong, but it keeps growing and then I need to truncate it.

Also number of binaries waiting to be converted is keep increasing also. WHat can I do to fix this? Many thanks.

>Completed adding 13 releases in 12.92 second(s). 646,287 binaries waiting to be converted

**Comment by DariusIII** [comment]
What is your QPS? How many groups, how many threads are set up?

**Comment by thebitllc** [comment]
40 groups, 2 binaries threads. QPS need to check.

**Comment by DariusIII** [comment]
And how many update releases threads?

**Comment by thebitllc** [comment]
>And how many update releases threads?

Just one.

**Comment by DariusIII** [comment]
It used to work fine. Keyword: used to :) 
Anyway, since changes i made for table per group that is not the case. I am working on something that might fix this, but i need more time.

**Comment by DariusIII** [comment]
Is this still an issue?

**Comment by shempe** [comment]
looks like:

[03/Mar/2015 10:47] [NOTICE] [1.66,1.00,0.94] [00H:00M:04S] [MEM:~~22MB] [PID:30281] [DB.queryExec] [SQLSTATE[HY000]: General error: 1442 Can't update table 'parts' in stored function/trigger because it is already used by statement which invoked this stored function/trigger.]
[03/Mar/2015 10:47] [SQL]    [1.66,1.00,0.94] [00H:00M:04S] [MEM:~~22MB] [PID:30281] [DB.queryExec] [DELETE parts, binaries FROM parts JOIN binaries ON binaries.ID = parts.binaryID WHERE releaseID = 4527386]

**Comment by DariusIII** [comment]
As far as i am aware i have removed the trigger from database. if i have not, just remove the trigger.

**Comment by shempe** [comment]
binaries trigger removed, looks better.

**Comment by thebitllc** [comment]
I will close for now. I do have a part table wipe every weekend though.
